# spark_etl/config/spark_config.yaml
spark:
  app_name: "OlistETL"
  master: "spark://spark-master:7077"
  config:
    "spark.sql.adaptive.enabled": "true"
    "spark.sql.adaptive.coalescePartitions.enabled": "true"
    "spark.jars.packages": "org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262"
    "spark.jars.packages": "${SPARK_JARS_PACKAGES}"
